paths = [
    "test\\to\\path1\\",
    "test\\to\\path2\\",   
    "test\\to\\path3\\",   
    "test\\to\\pat4\\", 
    "$(USERPROFILE)/test1919191919/",
]
envs = [
    ["TEST_ENV","$(USERPROFILE)/100"],
]
